#!/usr/bin/env python3
"""
Wordle CLI - Python
Terminal version with proper duplicate-letter handling.
"""

import random
import sys

# ANSI colors
GREEN = "\033[42m\033[30m"  # green background
YELLOW = "\033[43m\033[30m"  # yellow background
GRAY = "\033[100m\033[37m"  # gray background
RESET = "\033[0m"
BOLD = "\033[1m"

# 5-letter word list (400+ common words - add more if you like)
WORD_LIST = [
    "about",
    "above",
    "alert",
    "alike",
    "alive",
    "allow",
    "alone",
    "along",
    "alter",
    "among",
    "anger",
    "angle",
    "angry",
    "apple",
    "apply",
    "arena",
    "argue",
    "arise",
    "array",
    "aside",
    "asset",
    "audio",
    "audit",
    "avoid",
    "award",
    "aware",
    "badly",
    "baker",
    "bases",
    "basic",
    "basis",
    "beach",
    "began",
    "begin",
    "being",
    "below",
    "bench",
    "billy",
    "birth",
    "black",
    "blame",
    "blind",
    "block",
    "blood",
    "board",
    "boost",
    "booth",
    "bound",
    "brain",
    "brand",
    "bread",
    "break",
    "breed",
    "brief",
    "bring",
    "broad",
    "broke",
    "brown",
    "build",
    "built",
    "buyer",
    "cable",
    "calif",
    "carry",
    "catch",
    "cause",
    "chain",
    "chair",
    "chart",
    "chase",
    "cheap",
    "check",
    "chest",
    "chief",
    "child",
    "china",
    "chose",
    "civil",
    "claim",
    "class",
    "clean",
    "clear",
    "click",
    "clock",
    "close",
    "coach",
    "coast",
    "could",
    "count",
    "court",
    "cover",
    "craft",
    "crash",
    "cream",
    "crime",
    "cross",
    "crowd",
    "crown",
    "curve",
    "cycle",
    "daily",
    "dance",
    "dated",
    "dealt",
    "death",
    "debut",
    "delay",
    "depth",
    "doing",
    "doubt",
    "dozen",
    "draft",
    "drama",
    "drawn",
    "dream",
    "dress",
    "drill",
    "drink",
    "drive",
    "drove",
    "dying",
    "eager",
    "early",
    "earth",
    "eight",
    "elite",
    "empty",
    "enemy",
    "enjoy",
    "enter",
    "entry",
    "equal",
    "error",
    "event",
    "every",
    "exact",
    "exist",
    "extra",
    "faith",
    "false",
    "fault",
    "fiber",
    "field",
    "fifth",
    "fifty",
    "fight",
    "final",
    "first",
    "fixed",
    "flash",
    "fleet",
    "floor",
    "fluid",
    "focus",
    "force",
    "forth",
    "forty",
    "forum",
    "found",
    "frame",
    "frank",
    "fraud",
    "fresh",
    "front",
    "fruit",
    "fully",
    "funny",
    "giant",
    "given",
    "glass",
    "globe",
    "going",
    "grace",
    "grade",
    "grand",
    "grant",
    "grass",
    "great",
    "green",
    "gross",
    "group",
    "grown",
    "guard",
    "guess",
    "guest",
    "guide",
    "happy",
    "harry",
    "heart",
    "heavy",
    "hence",
    "henry",
    "horse",
    "hotel",
    "house",
    "human",
    "ideal",
    "image",
    "index",
    "inner",
    "input",
    "issue",
    "japan",
    "jimmy",
    "joint",
    "jones",
    "judge",
    "known",
    "label",
    "large",
    "laser",
    "later",
    "laugh",
    "layer",
    "learn",
    "lease",
    "least",
    "leave",
    "legal",
    "level",
    "lewis",
    "light",
    "limit",
    "links",
    "lives",
    "local",
    "logic",
    "loose",
    "lower",
    "lucky",
    "lunch",
    "lying",
    "magic",
    "major",
    "maker",
    "march",
    "maria",
    "match",
    "maybe",
    "mayor",
    "meant",
    "media",
    "metal",
    "might",
    "minor",
    "minus",
    "mixed",
    "model",
    "money",
    "month",
    "moral",
    "motor",
    "mount",
    "mouse",
    "mouth",
    "movie",
    "music",
    "needs",
    "never",
    "newly",
    "night",
    "noise",
    "north",
    "noted",
    "novel",
    "nurse",
    "occur",
    "ocean",
    "offer",
    "often",
    "order",
    "other",
    "ought",
    "paint",
    "panel",
    "paper",
    "party",
    "peace",
    "peter",
    "phase",
    "phone",
    "photo",
    "piece",
    "pilot",
    "pitch",
    "place",
    "plain",
    "plane",
    "plant",
    "plate",
    "point",
    "pound",
    "power",
    "press",
    "price",
    "pride",
    "prime",
    "print",
    "prior",
    "prize",
    "proof",
    "proud",
    "prove",
    "queen",
    "quick",
    "quiet",
    "quite",
    "radio",
    "raise",
    "range",
    "rapid",
    "ratio",
    "reach",
    "ready",
    "refer",
    "right",
    "rival",
    "river",
    "robin",
    "roger",
    "roman",
    "rough",
    "round",
    "route",
    "royal",
    "rural",
    "scale",
    "scene",
    "scope",
    "score",
    "sense",
    "serve",
    "seven",
    "shall",
    "shape",
    "share",
    "sharp",
    "sheet",
    "shelf",
    "shell",
    "shift",
    "shirt",
    "shock",
    "shoot",
    "short",
    "shown",
    "sight",
    "since",
    "sixth",
    "sixty",
    "sized",
    "skill",
    "sleep",
    "slide",
    "small",
    "smart",
    "smile",
    "smith",
    "smoke",
    "solid",
    "solve",
    "sorry",
    "sound",
    "south",
    "space",
    "spare",
    "speak",
    "speed",
    "spend",
    "spent",
    "split",
    "spoke",
    "sport",
    "staff",
    "stage",
    "stake",
    "stand",
    "start",
    "state",
    "steam",
    "steel",
    "stick",
    "still",
    "stock",
    "stone",
    "stood",
    "store",
    "storm",
    "story",
    "strip",
    "stuck",
    "study",
    "stuff",
    "style",
    "sugar",
    "suite",
    "super",
    "sweet",
    "table",
    "taken",
    "taste",
    "taxes",
    "teach",
    "teeth",
    "terry",
    "texas",
    "thank",
    "theft",
    "their",
    "theme",
    "there",
    "these",
    "thick",
    "thing",
    "think",
    "third",
    "those",
    "three",
    "threw",
    "throw",
    "tight",
    "times",
    "tired",
    "title",
    "today",
    "topic",
    "total",
    "touch",
    "tough",
    "tower",
    "track",
    "trade",
    "train",
    "treat",
    "trend",
    "trial",
    "tried",
    "tries",
    "truck",
    "truly",
    "trust",
    "truth",
    "twice",
    "twist",
    "tyler",
    "type",
    "typical",
    "uncle",
    "under",
    "undue",
    "union",
    "unity",
    "until",
    "upper",
    "upset",
    "urban",
    "usage",
    "usual",
    "valid",
    "value",
    "video",
    "virus",
    "visit",
    "vital",
    "voice",
    "waste",
    "watch",
    "water",
    "wheel",
    "where",
    "which",
    "while",
    "white",
    "whole",
    "whose",
    "woman",
    "women",
    "world",
    "worry",
    "worse",
    "worst",
    "worth",
    "would",
    "wound",
    "write",
    "wrong",
    "wrote",
    "yield",
    "young",
    "youth",
]


def color_letter(letter, status):
    if status == "green":
        return f"{GREEN} {letter.upper()} {RESET}"
    if status == "yellow":
        return f"{YELLOW} {letter.upper()} {RESET}"
    return f"{GRAY} {letter.upper()} {RESET}"


def evaluate_guess(guess, answer):
    result = ["gray"] * 5
    answer_chars = list(answer)

    # first pass: greens
    for i in range(5):
        if guess[i] == answer[i]:
            result[i] = "green"
            answer_chars[i] = None

    # second pass: yellows
    for i in range(5):
        if result[i] == "green":
            continue
        if guess[i] in answer_chars:
            result[i] = "yellow"
            answer_chars[answer_chars.index(guess[i])] = None

    return result


def print_board(guesses, results):
    print()
    for g, r in zip(guesses, results):
        line = "".join(color_letter(ch, st) for ch, st in zip(g, r))
        print(" " + line)
    print()


def main():
    answer = random.choice(WORD_LIST)
    max_tries = 6
    guesses = []
    results = []

    print(f"{BOLD}WORDLE CLI{RESET}")
    print("Guess the 5-letter word. You get 6 tries.")
    print(f"{GREEN} {RESET} = right letter, right spot")
    print(f"{YELLOW} {RESET} = right letter, wrong spot")
    print(f"{GRAY} {RESET} = not in word\n")

    while len(guesses) < max_tries:
        guess = input(f"Try {len(guesses) + 1}/{max_tries} > ").strip().lower()

        if guess == "quit":
            print(f"The word was: {answer.upper()}")
            sys.exit(0)
        if len(guess) != 5 or not guess.isalpha():
            print("Enter exactly 5 letters.")
            continue
        if guess not in WORD_LIST:
            confirm = input("Not in dictionary. Use anyway? (y/n) ").lower()
            if confirm != "y":
                continue

        res = evaluate_guess(guess, answer)
        guesses.append(guess)
        results.append(res)

        print_board(guesses, results)

        if guess == answer:
            print(f"{BOLD}You got it in {len(guesses)}!{RESET}")
            break
    else:
        print(f"Out of tries. The word was: {BOLD}{answer.upper()}{RESET}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nBye!")
